In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [ ]:
# Load dataset
iris = load_iris()
x=iris.data
y=iris.target

In [ ]:
# split
x_train, x_test, y_train, y_test = train_test_split(
    x,y, test_size=0.2, random_state=42
)

In [ ]:
# Decision treee model
dt=DecisionTreeClassifier(random_state=42)
dt.fit(x_train,y_train)
dt_pred=dt.predict(x_test)

In [ ]:
print("Decision Tree Accuracy:", accuracy_score(y_test,dt_pred))

Decision Tree Accuracy: 1.0


In [ ]:
rf=RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(x_train,y_train)
rf_pred=rf.predict(x_test)

In [ ]:
# Detailed report
print("\nRandom Forest confusion Matrix:\n", confusion_matrix(y_test, rf_pred))
print("\nRandom Forest Report:\n", classification_report(y_test,rf_pred))


Random Forest confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Random Forest Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

